### ISSUE TITLE
Alternate character variant of श्व (shwa) combination for Nepali 

### ISSUE THREAD

**Issue by PeterA** [silnrsi/font-annapurna#4]
In a word like विश्व (world) the shwa is rendered in a way that is fairly uncommon in Nepali writing. Here is a screenshot of how it appears in Annapurna SIL: 
![bishwa](https://user-images.githubusercontent.com/145472/62526141-61dcbd80-b858-11e9-8a9e-938794f64ddb.png)

Is development on this font closed or is it possible to add an alternate character variant for the श्व combination that would feel more natural to Nepali readers?

**Comment by mhosken** [comment]
It is always possible to submit issues. The font isn't necessarily in development at the moment. But if the number of issues rises enough, we would probably do some work on it. So do send your issues.

The most helpful issue reports give a character sequence, how it renders in the font for you and how you would expect it to render (e.g. from another font). It would also help to know whether this is a language specific request or considered to be a general problem for all languages using the font.

In this case, are you asking for a variant conjunct just for Nepali or for Indian usage as well? And what do you want this conjunct to look like (please make it good and big, say 100pt)?

**Comment by PeterA** [comment]
Thanks for the request for additional information. Here is the character combination used to create the conjunct and the conjunct in a larger size:

![shwa](https://user-images.githubusercontent.com/145472/62530528-758c2200-b860-11e9-9a3c-1159999b12c9.png)

I do not know about whether Hindi or Newari would use this alternate conjunct. I just know that in Nepali the proposed alternate is the more common way of combining those characters.

**Comment by jcoblentz** [comment]
The standard way to get the alternate rendering you want is to **insert ZWJ** (Zero Width Joiner) after the halant, as explained in chapter 12 of the Unicode standard. Here are some examples:
![image](https://user-images.githubusercontent.com/12460265/144492208-3667bd16-dd84-4b9d-adfa-ba50400a3e1a.png)


I don’t think the default Nepali or Hindi keyboards provided with Windows have keys for the ZWJ and JWNJ, but you can find a keyboard at https://keyman.com/ and search for a Devanagari keyboard. A keyboard found at https://keyman.com/keyboards/sil_devanagari_phonetic works well with a US keyboard. This keyboard has the plain halant on the semicolon key, halant+ZWJ on lower-case x, and halant+ZWNJ on upper-case X. That way all three options are readily available and easy to enter. 
There are other Devanagari Keyman keyboard layouts available so you can choose one that is comfortable for you. For each layout option, you can click the “Use keyboard online” button on its web page to try out the different layouts.
